# set "DOCKER_BUILDKIT=0" & docker-compose build
# docker run --rm -it id sh
# set "DOCKER_BUILDKIT=0" & docker build . -t spotifymanager:nx-base
version: "3.8"

networks:
  corp:
    driver: bridge

services:
  spotify_api:
    container_name: spotify_api
    image: staijn/spotifymanager:api
    ports:
      - 4901:3333
    networks:
      - corp
    restart: on-failure
    volumes:
      - /data/spotifymanager:/app/dist/apps/api/assets
  spotify_website:
    container_name: spotify_website
    image: staijn/spotifymanager:website
    ports:
      - 4900:80
    networks:
      - corp
    restart: on-failure
