// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotifyManager.Infrastructure.Persistence;

#nullable disable

namespace SpotifyManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SpotifyManagerDbContext))]
    [Migration("20260812195201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spotify_manager")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.EmailDigestLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<Guid[]>("IncludedChangeIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UserId", "DueAt");

                    b.ToTable("email_digest_logs", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.ForkedPlaylistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaselineSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalPlaylistId")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SourcePlaylistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaselineSnapshotId");

                    b.HasIndex("SourcePlaylistId");

                    b.HasIndex("Provider", "ExternalPlaylistId")
                        .IsUnique();

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("forked_playlists", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.NotificationSubscriptionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ForkedPlaylistId")
                        .HasColumnType("uuid");

                    b.Property<string>("IntervalConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IntervalKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastEvaluatedChangeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ForkedPlaylistId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Enabled", "NextDueAt");

                    b.ToTable("notification_subscriptions", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.PlaylistChangeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("FromPosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("FromSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("OccurrenceKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SourcePlaylistId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ToPosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("FromSnapshotId");

                    b.HasIndex("ToSnapshotId");

                    b.HasIndex("SourcePlaylistId", "CreatedAt");

                    b.ToTable("playlist_changes", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.PlaylistSnapshotItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Artists")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("DurationMilliseconds")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalTrackId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Isrc")
                        .HasColumnType("text");

                    b.Property<string>("OccurrenceKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RawMetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "OccurrenceKey")
                        .IsUnique();

                    b.HasIndex("SnapshotId", "Position")
                        .IsUnique();

                    b.ToTable("playlist_snapshot_items", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.PlaylistSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalVersion")
                        .HasColumnType("text");

                    b.Property<string>("RawMetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SourcePlaylistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourcePlaylistId", "ContentHash");

                    b.HasIndex("SourcePlaylistId", "ExternalVersion");

                    b.ToTable("playlist_snapshots", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.ProviderConnectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RawMetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("provider_connections", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.ScheduledWorkRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "DueAt");

                    b.HasIndex("WorkType", "TargetId", "Status");

                    b.ToTable("scheduled_work", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.SourcePlaylistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalOwnerId")
                        .HasColumnType("text");

                    b.Property<string>("ExternalPlaylistId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ExternalVersion")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ProviderConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderConnectionId", "Provider", "ExternalPlaylistId")
                        .IsUnique();

                    b.ToTable("source_playlists", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.UserTrackPreferenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalTrackId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Preference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider", "ExternalTrackId")
                        .IsUnique();

                    b.ToTable("user_track_preferences", "spotify_manager");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.EmailDigestLogRecord", b =>
                {
                    b.HasOne("SpotifyManager.Infrastructure.Persistence.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.ForkedPlaylistRecord", b =>
                {
                    b.HasOne("SpotifyManager.Infrastructure.Persistence.PlaylistSnapshotRecord", null)
                        .WithMany()
                        .HasForeignKey("BaselineSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SpotifyManager.Infrastructure.Persistence.SourcePlaylistRecord", "SourcePlaylist")
                        .WithMany()
                        .HasForeignKey("SourcePlaylistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpotifyManager.Infrastructure.Persistence.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePlaylist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.NotificationSubscriptionRecord", b =>
                {
                    b.HasOne("SpotifyManager.Infrastructure.Persistence.ForkedPlaylistRecord", null)
                        .WithMany()
                        .HasForeignKey("ForkedPlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyManager.Infrastructure.Persistence.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.PlaylistChangeRecord", b =>
                {
                    b.HasOne("SpotifyManager.Infrastructure.Persistence.PlaylistSnapshotRecord", null)
                        .WithMany()
                        .HasForeignKey("FromSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpotifyManager.Infrastructure.Persistence.SourcePlaylistRecord", null)
                        .WithMany()
                        .HasForeignKey("SourcePlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyManager.Infrastructure.Persistence.PlaylistSnapshotRecord", null)
                        .WithMany()
                        .HasForeignKey("ToSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.PlaylistSnapshotItemRecord", b =>
                {
                    b.HasOne("SpotifyManager.Infrastructure.Persistence.PlaylistSnapshotRecord", "Snapshot")
                        .WithMany("Items")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.PlaylistSnapshotRecord", b =>
                {
                    b.HasOne("SpotifyManager.Infrastructure.Persistence.SourcePlaylistRecord", "SourcePlaylist")
                        .WithMany()
                        .HasForeignKey("SourcePlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePlaylist");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.ProviderConnectionRecord", b =>
                {
                    b.HasOne("SpotifyManager.Infrastructure.Persistence.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.SourcePlaylistRecord", b =>
                {
                    b.HasOne("SpotifyManager.Infrastructure.Persistence.ProviderConnectionRecord", "ProviderConnection")
                        .WithMany()
                        .HasForeignKey("ProviderConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderConnection");
                });

            modelBuilder.Entity("SpotifyManager.Infrastructure.Persistence.PlaylistSnapshotRecord", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
