<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SpotifyManager.Application\SpotifyManager.Application.csproj" />
    <ProjectReference Include="..\..\src\SpotifyManager.Domain\SpotifyManager.Domain.csproj" />
    <ProjectReference Include="..\..\src\SpotifyManager.Infrastructure\SpotifyManager.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\SpotifyManager.Provider.Abstractions\SpotifyManager.Provider.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\SpotifyManager.Provider.Spotify\SpotifyManager.Provider.Spotify.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
